# Generated by Django 4.0.6 on 2022-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True, verbose_name='count'),
        ),
    ]
