# Generated by Django 4.0.6 on 2022-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.CharField(default=0, max_length=10, null=True, verbose_name='count'),
        ),
    ]
