# Generated by Django 4.0.6 on 2022-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_checkout_is_paied'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='shop.item'),
        ),
    ]
