# Generated by Django 4.0.6 on 2022-07-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_checkout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='door',
        ),
    ]
