# Generated by Django 4.0.6 on 2022-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_checkout_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_paied',
            field=models.BooleanField(default=False),
        ),
    ]
