# Generated by Django 4.0.6 on 2022-07-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_checkout_is_paied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
