# Generated by Django 4.0.6 on 2022-08-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_checkout_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='checkout',
            name='client_ip',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
