# Generated by Django 4.0.6 on 2022-08-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_checkout_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.ForeignKey(db_column='barcode', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', to_field='barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveBigIntegerField(db_index=True, unique=True),
        ),
    ]
