# Generated by Django 4.1 on 2022-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_item_product_item_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pay_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
