# Generated by Django 4.0.6 on 2022-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_review_for_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='for_view',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
